// <auto-generated />
using JhooneByUju.DataAccess.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JhooneByUju.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230509141835_addImageUrlToProductModel")]
    partial class addImageUrlToProductModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.3.23174.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("JhooneByUju.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 0,
                            Name = "Hand Bags"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 0,
                            Name = "Purses"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 0,
                            Name = "Belts"
                        },
                        new
                        {
                            Id = 4,
                            DisplayOrder = 0,
                            Name = "Arts"
                        });
                });

            modelBuilder.Entity("JhooneByUju.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ListPrice")
                        .HasColumnType("float");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<double>("Price15")
                        .HasColumnType("float");

                    b.Property<int>("StoreCode")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Second Hand bag created by Igboayaka Uju",
                            Designer = "Obianuju Igboayaka",
                            ImageUrl = "",
                            ListPrice = 14.0,
                            Price = 13.199999999999999,
                            Price15 = 11.0,
                            StoreCode = 102,
                            Title = "Hand Bags 2"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "First Hand bag created by Igboayaka Uju",
                            Designer = "Obianuju Igboayaka",
                            ImageUrl = "",
                            ListPrice = 35.0,
                            Price = 32.0,
                            Price15 = 27.0,
                            StoreCode = 101,
                            Title = "Hand Bag  1"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Description = "First around the waist belt created by Igboayaka Uju",
                            Designer = "Obianuju Igboayaka",
                            ImageUrl = "",
                            ListPrice = 27.0,
                            Price = 25.0,
                            Price15 = 22.0,
                            StoreCode = 201,
                            Title = "Belts 1"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Description = "First Art painting created by Igboayaka Uju",
                            Designer = "Obianuju Igboayaka",
                            ImageUrl = "",
                            ListPrice = 200.0,
                            Price = 187.0,
                            Price15 = 160.0,
                            StoreCode = 301,
                            Title = "Arts 1"
                        });
                });

            modelBuilder.Entity("JhooneByUju.Models.Product", b =>
                {
                    b.HasOne("JhooneByUju.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
